### PR TITLE
Major rewrite v1

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by arkilic** [comment]
Don't merge this yet. I have a few things to get working. Master works so no need to break it yet

**Comment by tacaswell** [comment]
It is just much easier to see changes as a diff

**Comment by arkilic** [comment]
Got it. I did not want to confuse anyone with this. I don't mind if you guys don't mind the noise it'll generate for a bit

**Comment by hhslepicka** [comment]
Is it good to go now? =D

**Comment by arkilic** [comment]
We will find out tmrw when we attempt what we left in half today

**Comment by arkilic** [comment]
Attn @hhslepicka 
Insert and find methods needed for your migration

**Comment by danielballan** [comment]
Cool. I looked at the notebook. It demos the header, tail, and the file upload feature. Can you also demo the Event equivalent in analysisstore so I can wrap my head around how that API works here?

**Comment by arkilic** [comment]
There should be another notebook. I think the one you see is prior to the refactor. I can put another notebook together if I haven't already done so(@hhslepicka has been using an example notebook for migrating his stuff). File upload feature is deprecated as we decided to use filestore links

**Comment by danielballan** [comment]
Oh OK. I was looking at the first file added by this PR. Should it be deleted? https://github.com/arkilic/analysisstore/blob/04af80bf19e1deb18817018c51399ff92935d59f/Analaysisstore%20notebook.ipynb

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Aug 2, 2016 at 8:12 AM -0400, "Arman Arkilic" <notifications@github.com<mailto:notifications@github.com>> wrote:


There should be another notebook. I think the one you see is prior to the refactor. I can put another notebook together if I haven't already done so(@hhslepicka<https://github.com/hhslepicka> has been using an example notebook for migrating his stuff). File upload feature is deprecated as we decided to use filestore links

**Comment by arkilic** [comment]
Yes, I need to delete the old one. I had two notebooks that I was looking at via vim so I didn't know which one which so kept both before I got off the train :)
________________________________________

**Comment by danielballan** [comment]
Cool. Is [this](https://github.com/arkilic/analysisstore/blob/04af80bf19e1deb18817018c51399ff92935d59f/Simple%20Analysisstore%20notebook.ipynb) the notebook we should be reviewing?

**Pull request merged**
